def includeme(config):
    config.add_static_view('static', 'static',cache_max_age=3600 )
    config.add_route('home', '/')
    config.add_route('login', '/login')
    config.add_route('register', '/register')
    config.add_route('profile', '/profile')
    config.add_route('logout', '/logout')
    config.add_route('login_github', 'auth/github')
    config.add_route('login_discord', 'auth/discord')
    config.add_route('login_google', 'auth/google')
    config.add_route('auth', '/auth')
    config.add_route('refresh', '/refresh')
    config.add_route('forgot_password', '/forgot_password')
    config.add_route('reset_password', '/reset_password')

